server:
  port: 8084

spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: SERVICE-PROFESSEUR
  application:
    name: SERVICE-PROFESSEUR
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gcs_professeur?createDatabaseIfNotExist=true
    username: "root"
    password: "root"
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

